export const ROUTES = {
  home: '/',
  bestSellers: '/collections/best-sellers',
  collections: '/collections',
  templates: '/pages/templates',
  presets: '/pages/presets',
  b2b: '/pages/b2b-features',
  search: '/search',
  account: '/account',
  cart: '/cart',
  shipping: '/policies/shipping-policy',
  privacy: '/policies/privacy-policy',
  returns: '/policies/refund-policy',
  terms: '/policies/terms-of-service',
  faqs: '/pages/faqs',
  about: '/pages/about-us',
  bookTreatment: '/pages/book-a-treatment',
  promotions: '/pages/promotion-programs',
  promises: '/pages/our-promises',
  contact: '/pages/contact',
}
